services:
  - type: web
    name: financial-tracker
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      - key: PORT
        value: 3000
      - key: BANGKOK_BANK_API_URL
        value: https://api.bangkokbank.com/transactions
      - key: BANGKOK_BANK_API_TOKEN
        value: 9bceac5a32e640bcb78bfaf5edc61ff1
      - key: SCB_EASY_API_URL
        value: https://api.scb.co.th/transactions
      - key: SCB_EASY_API_TOKEN
        value: l782b452c1d85240edbb1a18da225bef7c
      - key: KPLUS_API_URL
        value: https://api.kasikornbank.com/kplus/transactions
      - key: KPLUS_API_TOKEN
        value: D1Y4GVCEaf38AYz2cDbD6dwclFm5U051
      - key: MAKE_BY_KBANK_API_URL
        value: https://api.kasikornbank.com/make/transactions
      - key: MAKE_BY_KBANK_API_TOKEN
        value: D1Y4GVCEaf38AYz2cDbD6dwclFm5U051
