services:
  - type: web
    name: financial-tracker
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      - key: PORT
        value: 3000
      - key: BANGKOK_BANK_API_URL
        value: ${BANGKOK_BANK_API_URL}
      - key: BANGKOK_BANK_API_TOKEN
        value: ${BANGKOK_BANK_API_TOKEN}
      - key: SCB_EASY_API_URL
        value: ${SCB_EASY_API_URL}
      - key: SCB_EASY_API_TOKEN
        value: ${SCB_EASY_API_TOKEN}
      - key: KPLUS_API_URL
        value: ${KPLUS_API_URL}
      - key: KPLUS_API_TOKEN
        value: ${KPLUS_API_TOKEN}
      - key: MAKE_BY_KBANK_API_URL
        value: ${MAKE_BY_KBANK_API_URL}
      - key: MAKE_BY_KBANK_API_TOKEN
        value: ${MAKE_BY_KBANK_API_TOKEN}
